#!/usr/bin/env python3
"""
train_rl_model.py — Train EfficientNet-B0 multi-input regression for RL/Qd.

Architecture:
    Image ROI → EfficientNet-B0 → 1280-dim features
    Scalar [5] → concat → FC(512) → ReLU → Dropout(0.3) → FC(2) → [RL, Qd]

Loss: HuberLoss (robust to outliers)
Optimizer: AdamW with CosineAnnealingLR
Mixed precision with CUDA version guard.

Usage:
    python3 train_rl_model.py --epochs 50 --batch 32
    python3 train_rl_model.py --epochs 1 --batch 8 --fast
"""

from __future__ import annotations

import argparse
import csv
import os
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import cv2
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm

from config import (
    MODEL_DIR,
    PROCESSED_DIR,
    PROJECT_ROOT,
    RL_MODEL_PATH,
    RL_ONNX_PATH,
    RL_QD_LABELS_CSV,
    RL_NORM_MIN,
    RL_NORM_MAX,
    TrainConfig,
)
from src.utils.logger import logger


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class RLDataset(Dataset):
    """Dataset for RL/Qd regression training.

    Loads cropped ROIs (from full images using bbox) plus scalar features
    and synthetic RL/Qd labels from the CSV generated by dataset_preparation.py.

    Parameters
    ----------
    csv_path : Path
        Path to ``rl_qd_labels.csv``.
    img_size : int
        Square image size for EfficientNet input.
    split : str
        ``"train"`` or ``"val"`` — filters rows by image path prefix.
    """

    def __init__(
        self,
        csv_path: Path = RL_QD_LABELS_CSV,
        img_size: int = 224,
        split: str = "train",
    ) -> None:
        self.img_size = img_size
        self.records: List[Dict] = []

        with open(csv_path, newline="") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                # Filter by split (train/val/test in image path)
                if f"/{split}/" in row["image_path"]:
                    self.records.append(row)

        logger.info(f"RLDataset ({split}): {len(self.records)} samples")

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """Return (image_tensor, scalar_tensor, target_tensor).

        Returns
        -------
        Tuple[torch.Tensor, torch.Tensor, torch.Tensor]
            - image: ``(3, 224, 224)`` normalised
            - scalars: ``(5,)``
            - targets: ``(2,)`` ``[rl_label, qd_label]``
        """
        rec = self.records[idx]

        # Load and crop image
        img_path = PROJECT_ROOT / rec["image_path"]
        img = cv2.imread(str(img_path))
        if img is None:
            img = np.zeros((self.img_size, self.img_size, 3), dtype=np.uint8)
        else:
            # Crop bbox from image (YOLO format: cx, cy, w, h normalised)
            h, w = img.shape[:2]
            cx = float(rec["bbox_x"]) * w
            cy = float(rec["bbox_y"]) * h
            bw = float(rec["bbox_w"]) * w
            bh = float(rec["bbox_h"]) * h
            x1 = max(0, int(cx - bw / 2) - 10)
            y1 = max(0, int(cy - bh / 2) - 10)
            x2 = min(w, int(cx + bw / 2) + 10)
            y2 = min(h, int(cy + bh / 2) + 10)
            img = img[y1:y2, x1:x2]
            if img.size == 0:
                img = np.zeros((self.img_size, self.img_size, 3), dtype=np.uint8)

        img = cv2.resize(img, (self.img_size, self.img_size))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0
        # ImageNet normalisation
        mean = np.array([0.485, 0.456, 0.406])
        std = np.array([0.229, 0.224, 0.225])
        img = (img - mean) / std
        img_tensor = torch.from_numpy(img).permute(2, 0, 1).float()

        # Scalar features (normalised for stable training)
        raw_dist = float(rec["simulated_distance"])
        raw_tilt = float(rec["simulated_tilt"])
        raw_hum = float(rec["simulated_humidity"])
        scalars = torch.tensor([
            raw_dist / 5000.0,    # normalise distance to ~[0, 1]
            raw_tilt / 10.0,      # normalise tilt to ~[0, 1]
            25.0 / 50.0,          # normalise temperature
            raw_hum / 100.0,      # normalise humidity
            0.0,                  # is_night
        ], dtype=torch.float32)

        # Targets — normalise RL to [0, 1], Qd already in [0, 1]
        rl_label = float(rec["rl_label"])
        qd_label = float(rec["qd_label"])
        rl_norm = (rl_label - RL_NORM_MIN) / (RL_NORM_MAX - RL_NORM_MIN)
        rl_norm = max(0.0, min(1.0, rl_norm))
        targets = torch.tensor([
            rl_norm,
            qd_label,
        ], dtype=torch.float32)

        return img_tensor, scalars, targets


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

class RLRegressorModel(nn.Module):
    """EfficientNet-B0 + scalar fusion for RL/Qd regression.

    Parameters
    ----------
    scalar_dim : int
        Number of scalar input features.
    hidden_dim : int
        Hidden layer size in the fusion head.
    dropout : float
        Dropout probability.
    """

    def __init__(
        self,
        scalar_dim: int = 5,
        hidden_dim: int = 512,
        dropout: float = 0.3,
    ) -> None:
        super().__init__()
        try:
            from efficientnet_pytorch import EfficientNet

            self.backbone = EfficientNet.from_pretrained("efficientnet-b0")
            backbone_out = 1280
        except ImportError:
            logger.warning("efficientnet_pytorch not found — using torchvision MobileNetV2")
            from torchvision.models import mobilenet_v2, MobileNet_V2_Weights

            base = mobilenet_v2(weights=MobileNet_V2_Weights.DEFAULT)
            self.backbone = nn.Sequential(
                base.features,
                nn.AdaptiveAvgPool2d(1),
                nn.Flatten(),
            )
            backbone_out = 1280

        self.head = nn.Sequential(
            nn.Linear(backbone_out + scalar_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, 2),
        )

    def forward(self, image: torch.Tensor, scalars: torch.Tensor) -> torch.Tensor:
        """Forward pass.

        Parameters
        ----------
        image : torch.Tensor
            ``(B, 3, 224, 224)``
        scalars : torch.Tensor
            ``(B, 5)``

        Returns
        -------
        torch.Tensor
            ``(B, 2)`` → ``[RL, Qd]``
        """
        if hasattr(self.backbone, "extract_features"):
            feats = self.backbone.extract_features(image)
            feats = nn.functional.adaptive_avg_pool2d(feats, 1).flatten(1)
        else:
            feats = self.backbone(image)
        fused = torch.cat([feats, scalars], dim=1)
        return self.head(fused)


# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------

def train(
    epochs: int = 50,
    batch_size: int = 32,
    lr: float = 1e-4,
    weight_decay: float = 1e-5,
    patience: int = 10,
    fast: bool = False,
) -> Path:
    """Train the RL regression model.

    Parameters
    ----------
    epochs : int
        Maximum number of training epochs.
    batch_size : int
        Mini-batch size.
    lr : float
        Learning rate.
    weight_decay : float
        AdamW weight decay.
    patience : int
        Early-stopping patience.
    fast : bool
        Limit to first 200 samples per split for quick validation.

    Returns
    -------
    Path
        Path to the saved best model checkpoint.
    """
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    logger.info(f"Training on device: {device}")

    # Datasets
    train_ds = RLDataset(split="train")
    val_ds = RLDataset(split="val")

    if fast:
        train_ds.records = train_ds.records[:200]
        val_ds.records = val_ds.records[:50]

    train_loader = DataLoader(
        train_ds, batch_size=batch_size, shuffle=True,
        num_workers=2, pin_memory=True, drop_last=True,
    )
    val_loader = DataLoader(
        val_ds, batch_size=batch_size, shuffle=False,
        num_workers=2, pin_memory=True,
    )

    # Model
    model = RLRegressorModel().to(device)
    criterion = nn.HuberLoss(delta=0.1)  # tuned for normalised [0,1] targets
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    # Mixed precision
    use_amp = device.type == "cuda"
    scaler = None
    if use_amp:
        try:
            scaler = torch.amp.GradScaler("cuda")
        except Exception:
            scaler = torch.cuda.amp.GradScaler()

    # TensorBoard
    tb_writer = None
    try:
        from torch.utils.tensorboard import SummaryWriter

        tb_dir = PROJECT_ROOT / "runs" / "rl_regressor"
        tb_writer = SummaryWriter(str(tb_dir))
    except ImportError:
        pass

    best_val_loss = float("inf")
    no_improve = 0
    RL_MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)

    for epoch in range(1, epochs + 1):
        # --- Train ---
        model.train()
        train_loss = 0.0
        for images, scalars, targets in tqdm(train_loader, desc=f"Epoch {epoch}/{epochs} [train]"):
            images = images.to(device)
            scalars = scalars.to(device)
            targets = targets.to(device)

            optimizer.zero_grad()

            if use_amp and scaler is not None:
                with torch.amp.autocast("cuda"):
                    preds = model(images, scalars)
                    loss = criterion(preds, targets)
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()
            else:
                preds = model(images, scalars)
                loss = criterion(preds, targets)
                loss.backward()
                optimizer.step()

            train_loss += loss.item()

        scheduler.step()
        avg_train = train_loss / max(len(train_loader), 1)

        # --- Validate ---
        model.eval()
        val_loss = 0.0
        rl_errors, qd_errors = [], []
        with torch.no_grad():
            for images, scalars, targets in val_loader:
                images = images.to(device)
                scalars = scalars.to(device)
                targets = targets.to(device)
                preds = model(images, scalars)
                loss = criterion(preds, targets)
                val_loss += loss.item()

                # Per-metric errors (denormalise RL for meaningful MAE)
                rl_scale = RL_NORM_MAX - RL_NORM_MIN
                rl_err = ((preds[:, 0] - targets[:, 0]) * rl_scale).abs().cpu().numpy()
                qd_err = (preds[:, 1] - targets[:, 1]).abs().cpu().numpy()
                rl_errors.extend(rl_err.tolist())
                qd_errors.extend(qd_err.tolist())

        avg_val = val_loss / max(len(val_loader), 1)
        rl_mae = float(np.mean(rl_errors)) if rl_errors else 0.0
        qd_mae = float(np.mean(qd_errors)) if qd_errors else 0.0
        rl_rmse = float(np.sqrt(np.mean(np.array(rl_errors) ** 2))) if rl_errors else 0.0

        logger.info(
            f"Epoch {epoch}: train_loss={avg_train:.4f} val_loss={avg_val:.4f} "
            f"RL_MAE={rl_mae:.2f} RL_RMSE={rl_rmse:.2f} Qd_MAE={qd_mae:.4f}"
        )

        if tb_writer:
            tb_writer.add_scalar("Loss/train", avg_train, epoch)
            tb_writer.add_scalar("Loss/val", avg_val, epoch)
            tb_writer.add_scalar("Metrics/RL_MAE", rl_mae, epoch)
            tb_writer.add_scalar("Metrics/RL_RMSE", rl_rmse, epoch)
            tb_writer.add_scalar("Metrics/Qd_MAE", qd_mae, epoch)
            tb_writer.add_scalar("LR", scheduler.get_last_lr()[0], epoch)

        # Early stopping / checkpoint
        if avg_val < best_val_loss:
            best_val_loss = avg_val
            no_improve = 0
            torch.save(model.state_dict(), RL_MODEL_PATH)
            logger.info(f"  ✓ Best model saved → {RL_MODEL_PATH}")
        else:
            no_improve += 1
            if no_improve >= patience:
                logger.info(f"Early stopping at epoch {epoch} (patience={patience})")
                break

    # --- ONNX export ---
    try:
        model.load_state_dict(torch.load(RL_MODEL_PATH, map_location=device, weights_only=True))
        model.eval()
        dummy_img = torch.randn(1, 3, 224, 224).to(device)
        dummy_sc = torch.randn(1, 5).to(device)
        RL_ONNX_PATH.parent.mkdir(parents=True, exist_ok=True)
        torch.onnx.export(
            model,
            (dummy_img, dummy_sc),
            str(RL_ONNX_PATH),
            input_names=["image", "scalars"],
            output_names=["prediction"],
            dynamic_axes={"image": {0: "batch"}, "scalars": {0: "batch"}, "prediction": {0: "batch"}},
            opset_version=17,
        )
        logger.info(f"ONNX model exported → {RL_ONNX_PATH}")
    except Exception as exc:
        logger.warning(f"ONNX export failed: {exc}")

    if tb_writer:
        tb_writer.close()

    logger.info("Training complete.")
    return RL_MODEL_PATH


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train RL/Qd regressor")
    cfg = TrainConfig()
    parser.add_argument("--epochs", type=int, default=cfg.rl_epochs)
    parser.add_argument("--batch", type=int, default=cfg.rl_batch)
    parser.add_argument("--lr", type=float, default=cfg.rl_lr)
    parser.add_argument("--patience", type=int, default=cfg.rl_patience)
    parser.add_argument("--fast", action="store_true", help="Quick 1-epoch test")
    args = parser.parse_args()

    if args.fast:
        args.epochs = 1
        args.batch = 8

    train(
        epochs=args.epochs,
        batch_size=args.batch,
        lr=args.lr,
        patience=args.patience,
        fast=args.fast,
    )
